### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.apache.maven:maven-project:jar

### ISSUE THREAD

**Issue by Bing-ok** [mojohaus/extra-enforcer-rules#121] opened 2020-11-28 11:54 UTC
## Issue description
Hi, there are multiple versions of **_org.apache.maven:maven-project_** in **_extra-enforcer-rules_**. As shown in the following dependency tree, according to Maven's “first declaration wins” strategy, only **_org.apache.maven:maven-project:2.0.9_** can be loaded, and **_org.apache.maven:maven-project:2.2.0_** will be shadowed.

However, several methods defined in shadowed version **_org.apache.maven:maven-project:2.2.0_** are referenced  by client project via **_org.apache.maven.shared:maven-dependency-tree:2.1_**, but missing in the actually loaded version **_org.apache.maven:maven-project:2.0.9_**.

For instance, the following missing method(defined in **_org.apache.maven:maven-project:2.2.0_**) are actually referenced by **_extra-enforcer-rules_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_extra-enforcer-rules_**.

**_org.apache.maven.project.MavenProject: org.apache.maven.project.ProjectBuilderConfiguration getProjectBuilderConfiguration()_** is invoked by **_extra-enforcer-rules_** via the following path:
<pre><code>
paths------
&lt;org.apache.maven.plugins.enforcer.BanCircularDependencies: java.util.Set getDependenciesToCheck(org.apache.maven.project.MavenProject)&gt; extra-enforcer-rules\target\classes
&lt;org.apache.maven.shared.dependency.graph.internal.Maven2DependencyGraphBuilder: org.apache.maven.shared.dependency.graph.DependencyNode buildDependencyGraph(org.apache.maven.project.MavenProject,org.apache.maven.artifact.resolver.filter.ArtifactFilter)>&gt; Repositories\org\apache\maven\shared\maven-dependency-tree\2.1\maven-dependency-tree-2.1.jar
&lt;org.apache.maven.shared.dependency.tree.DefaultDependencyTreeBuilder: org.apache.maven.shared.dependency.tree.DependencyNode buildDependencyTree(org.apache.maven.project.MavenProject)&gt; Repositories\org\apache\maven\shared\maven-dependency-tree\2.1\maven-dependency-tree-2.1.jar
&lt;org.apache.maven.project.MavenProject: org.apache.maven.project.ProjectBuilderConfiguration getProjectBuilderConfiguration()&gt;
</code></pre>

## Suggested fixing solutions
1. Upgrade dependency **_org.apache.maven.shared:maven-dependency-tree_** from **_2.1_** to **_2.2_**.  Because the newer version **_org.apache.maven.shared:maven-dependency-tree:2.2_** does not invoke the above missing method, such upgrading can solve the problem.
2. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library **_org.apache.maven:maven-project_** to be **_2.2.0_** in **_extra-enforcer-rules_**'s pom file.
3. Declare a direct dependency **_org.apache.maven:maven-project:2.2.0_** in the pom file of **_extra-enforcer-rules_**.
4. Use &lt;exclude&gt; to exclude **_org.apache.maven:maven-project:2.0.9_** from the dependency tree, so version **_2.2.0_** will be loaded.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
org.codehaus.mojo:extra-enforcer-rules:jar:1.4-SNAPSHOT
+- org.apache.maven:maven-core:jar:2.0.9:compile
|  \- <b>org.apache.maven:maven-project:jar:2.0.9:compile</b>
\- org.apache.maven.shared:maven-dependency-tree:jar:2.1:compile
   \- <b>(org.apache.maven:maven-project:jar:2.2.0:compile - omitted for conflict with 2.0.9)</b>
</code></pre>

**Comment by gmshake** [comment] 2020-11-30 02:56
The second solution sounds good enough :)

**Comment by Bing-ok** [comment] 2020-12-01 07:23
@mfriedenhagen Could you please help me review this issue? Thank you very much.

**Comment by mfriedenhagen** [comment] 2020-12-04 18:08
Hello @Bing-ok, 

first of all, thanks for detecting, analyzing reporting this. If I understand you correctly, you encountered real NPEs while using `extra-enforcer-rules`, do you not?

I do not think that the code in `extra-enforcer-rules` itself does rely _directly_ on such methods, otherwise the code would not compile and the invoker tests would fail.

I just checked out the current `master` myself and ran `mvn clean verify` using JDK 1.8 successfully, so we are missing an invoker test here. 

The least intrusive variant would be 2. as @gmshake pointed out. 

You should add an invoker test with the rule which fails right now and see whether the failure is fixed by managing the version up.

**Comment by mfriedenhagen** [comment] 2020-12-04 18:39
I put a breakpoint at https://github.com/mojohaus/extra-enforcer-rules/blob/149c131186bcfa8fc5d7ec496409affcc17e0059/src/main/java/org/apache/maven/plugins/enforcer/BanCircularDependencies.java#L138-L138

After running `mvn verify` I now just switched into target/it/circular-simple.

In that directory I now ran `mvnDebug enforcer:enforce`, connected my IDE and let it run to the breakpoint.

Using `lsof` I now see:

```
java    99361 mifr   58r   REG                1,5    31388             9977105 /Users/mifr/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4/maven-enforcer-plugin-1.4.jar
java    99361 mifr   61r   REG                1,5    63566             2782232 /Users/mifr/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
```

so it seems that the Maven version you use might make a difference as well. Mine is 3.6.3.

https://github.com/mojohaus/extra-enforcer-rules/blob/149c131186bcfa8fc5d7ec496409affcc17e0059/src/main/java/org/apache/maven/plugins/enforcer/BanCircularDependencies.java#L138-L138

**Comment by Bing-ok** [comment] 2020-12-07 11:35
I test master branch of the project. I see **_org.apache.maven.shared:maven-dependency-tree_** use **_2.1_** as the dependency tree I showed above.

**Comment by mfriedenhagen** [comment] 2020-12-07 17:55
Please state the Maven and `maven-enforcer-plugin` version you do use.

**Comment by Bing-ok** [comment] 2020-12-08 02:32
@mfriedenhagen Thanks for your support! I use Maven-3.6.3 and maven-enforcer-plugin-1.4. After reproducing steps you provided, I can see **_maven-dependency-tree_** is managed to 2.2.

**Comment by mfriedenhagen** [comment] 2020-12-08 07:44
Great, so @Bing-ok, would you please provide a small test project to show how you run into this situation? Take `circular-simple` as an example, no Java code is needed, just some incompatible combination of dependencies.

**Comment by Bing-ok** [comment] 2020-12-08 12:47
I run into this situation by the invoke path shown above.

**Comment by mfriedenhagen** [comment] 2020-12-10 08:06
This you did already explain in the original issue. But how do end up like this? Are you using an old version of Maven? Or of the enforcer-plugin? Sorry, but I will close this issue unless you show me something reproducible. 
I mean obviously the rule just works as intended under "normal" circumstances as the invoker test proves. 
How do you invoke `BanCircularDependencies` here?

**Closed** 2021-11-30 02:11 UTC
